workaround a bug in libboost that will fail if LC_ALL or LANG are uncorrectly set:
see https://svn.boost.org/trac/boost/ticket/4688 for more details

Signed-off-by: Niv Sardi <xaiki@evilgiggle.com>

diff --git a/debian/ndnsec-tools.postinst b/debian/ndnsec-tools.postinst
--- a/debian/ndnsec-tools.postinst
+++ b/debian/ndnsec-tools.postinst
@@ -11,10 +11,15 @@ if [ "$1" = configure ]; then
       --group \
       ndn-user
 
-  if ! su -s /bin/sh ndn-user -c ndnsec-get-default >/dev/null
-  then # generate keys for this machine
-    su -s /bin/sh ndn-user -c 'ndnsec-keygen /localhost/operator | ndnsec-install-cert -'
-  fi
+  su -s /bin/sh ndn-user -c '
+  # workaround a bug in libboost that will fail if LC_ALL or LANG are
+  # uncorrectly set: https://svn.boost.org/trac/boost/ticket/4688
+  unset LC_ALL
+  export LANG=C
+
+  if ! ndnsec-get-default >/dev/null; then # generate keys for this machine
+    ndnsec-keygen /localhost/operator | ndnsec-install-cert -
+  fi'
 
   # support EOS
   if [ -f /etc/lsb-release ]; then
